Switch dynamic version handling from pkg_resources (in setuptools) to packaging
This fixes following `ModuleNotFoundError` resulting from missing
dependency on setuptools:

    % rye add pygrib --path /path/to/repo
    % rye sync
    % rye run python -c 'import pygrib'
    ModuleNotFoundError: No module named 'pkg_resources'

In the executable code of pygrib, setuptools is only used for version
comparison purposes, and since setuptools is larger than necessary, this
commit replaces it with packaging, which is a more compact module
containing reusable core utilities for Python packaging compliant with
recent PEPs.